# this file is here to facilitate development/testing
# $ docker compose up -d --build --force-recreate

services:
  # postgres:
  #   image: postgres:14
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password

  backup:
    image: shynfard/pgbackups3
    environment:
      SCHEDULE: '@daily'     # optional
      BACKUP_KEEP_DAYS: 7     # optional
      # PASSPHRASE: passphrase  # optional
      S3_ENDPOINT: https://s3.agio360.com
      # S3_REGION: eu-center-netcup1
      S3_ACCESS_KEY_ID: i97wpHtecF4bQGc2
      S3_SECRET_ACCESS_KEY: TGvkABhgVdRlOnHuGdg6P2LGoTEwzIBH
      S3_BUCKET: backups
      S3_PREFIX: test
      POSTGRES_HOST: 192.168.178.4
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uWW3tyWCP7sR
